In [1]:
from data  import create_dataloader, VisA, MVTecAD
import pandas as pd
import cv2
import numpy as np
import os
os.chdir("/workspace/")

In [2]:
data_set = VisA(
    datadir='./dataset/VisA',
    target='candle',
    train=False,
    img_size=256,
    texture_source_dir='./dataset/dtd/images',
    grid_size=8,
    perlin_noise_threshold=0.5,
    textual_or_structural='structural',
    transparency_range=[0.15, 1.0],
    self_aug='self-augmentation'
)

data_set_2 = MVTecAD(
    datadir='./dataset/mvtec_ad',
    target='capsule',
    train=False,
    img_size=256,
    texture_source_dir='./dataset/dtd/images',
    grid_size=8,
    perlin_noise_threshold=0.5,
    textual_or_structural='structural',
    transparency_range=[0.15, 1.0],
    self_aug='self-augmentation'
)

In [3]:
img_1, mask_1, target_1 = data_set[199]
img_2, mask_2, target_2 = data_set_2[0]

In [6]:
# only object is candle
data_df = pd.read_csv(os.path.join("./dataset/VisA","split_csv","1cls.csv"))
data_df = data_df[data_df['object'] == 'candle']


In [26]:
mask = cv2.imread(os.path.join("./dataset/VisA",data_df["mask"][1099]))
mask = cv2.resize(mask, dsize=(256,256)).astype(bool).astype(int)
# to one channel
mask = mask[:,:,0]
mask.shape

NameError: name 'data_df' is not defined

In [21]:
mask_1[i][j] != np.array([0,0,0])

array([False, False, False])

In [24]:
mask_1[144][68]

array([1, 1, 1])

In [25]:
# show where mask_1 value is not 0
mask_1 = mask_1.astype(bool).astype(int)
for i in range(256):
    for j in range(256):
        if np.any(mask_1[i][j] != np.array([0,0,0])):
            print(mask_1[i][j])

[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]


In [24]:
img_size = (256,256)
# 3 channels
img = np.zeros((img_size[0],img_size[1],3)).astype(bool).astype(int)

In [25]:
img.shape

(256, 256, 3)

In [10]:
data_df["mask"][1099]

'candle/Data/Masks/Anomaly/099.png'

In [21]:
# reset index
data_df[data_df["split"]=="train"].reset_index(drop=True)

object  split   label                               image mask
0    candle  train  normal  candle/Data/Images/Normal/0836.JPG  NaN
1    candle  train  normal  candle/Data/Images/Normal/0451.JPG  NaN
2    candle  train  normal  candle/Data/Images/Normal/0516.JPG  NaN
3    candle  train  normal  candle/Data/Images/Normal/0977.JPG  NaN
4    candle  train  normal  candle/Data/Images/Normal/0249.JPG  NaN
..      ...    ...     ...                                 ...  ...
895  candle  train  normal  candle/Data/Images/Normal/0872.JPG  NaN
896  candle  train  normal  candle/Data/Images/Normal/0968.JPG  NaN
897  candle  train  normal  candle/Data/Images/Normal/0324.JPG  NaN
898  candle  train  normal  candle/Data/Images/Normal/0152.JPG  NaN
899  candle  train  normal  candle/Data/Images/Normal/0947.JPG  NaN

[900 rows x 5 columns]

In [41]:
data_df = data_df[data_df["split"]=="test"].reset_index(drop=True)

In [42]:
os.path.join(data_dir,data_df["mask"][195])

'./dataset/VisA/candle/Data/Masks/Anomaly/095.png'

In [56]:
data_df.tail()

object split    label                               image  \
195  candle  test  anomaly  candle/Data/Images/Anomaly/095.JPG   
196  candle  test  anomaly  candle/Data/Images/Anomaly/096.JPG   
197  candle  test  anomaly  candle/Data/Images/Anomaly/097.JPG   
198  candle  test  anomaly  candle/Data/Images/Anomaly/098.JPG   
199  candle  test  anomaly  candle/Data/Images/Anomaly/099.JPG   

                                  mask  
195  candle/Data/Masks/Anomaly/095.png  
196  candle/Data/Masks/Anomaly/096.png  
197  candle/Data/Masks/Anomaly/097.png  
198  candle/Data/Masks/Anomaly/098.png  
199  candle/Data/Masks/Anomaly/099.png

In [70]:
# check if data_df["mask"][195] is NaN
data_df["label"][0]

'normal'

In [45]:
import numpy as np